services:
  generator1:
    build:
      context: .
      dockerfile: distributed-id-generator/Dockerfile
    environment:
      - MACHINE_ID=0
      - DATACENTER_ID=1
    ports:
      - "8080:8080"

  generator2:
    build:
      context: .
      dockerfile: distributed-id-generator/Dockerfile
    environment:
      - MACHINE_ID=1
      - DATACENTER_ID=1
    ports:
      - "8081:8080"

  generator3:
    build:
      context: .
      dockerfile: distributed-id-generator/Dockerfile
    environment:
      - MACHINE_ID=2
      - DATACENTER_ID=2
    ports:
      - "8082:8080"
